site_name: 笔记mkdocs
copyright: Copyright (c) 2021 无为徐生  书法练习轨迹

theme:
  name: spacelab
  
nav: 
  - 我的笔记: 我的笔记/note.md
  - 书法练习:
    - 书法练习轨迹--明月几时有: 书法练习/书法练习轨迹--明月几时有.md
    - 书法练习轨迹ReadMe: 书法练习/书法练习轨迹ReadMe.md
    - 笔名汉字频率分析: 书法练习/笔名汉字频率分析.md
    - 古文诗词: 书法练习/古文诗词.md
    - 多宝塔碑: 书法练习/多宝塔碑.md
  - java资料:
    - gitNote: java资料/gitNote.md
    - javaNote: java资料/javaNote.md
    - linuxNote: java资料/linuxNote-x.md
    