site_name: note

theme:
  name: spacelab
  
nav: 
  - 我的笔记:
    - note: 我的笔记/note.md
  - 书法练习:
    - 书法练习轨迹ReadMe: 书法练习/书法练习轨迹ReadMe.md
    - 书法练习轨迹--明月几时有: 书法练习/书法练习轨迹--明月几时有.md
    - 笔名汉字频率分析: 书法练习/笔名汉字频率分析.md
    - 古文诗词: 书法练习/古文诗词.md
  - java资料:
    - java: java资料/java.md
    - gitNote: java资料/gitNote.md
    - linuxNote: java资料/linuxNote-x.md